(global-set-key (kbd "C-c b") 'bm-toggle)
(global-set-key (kbd "C-c n") 'bm-next)
(global-set-key (kbd "C-c p") 'bm-previous)
(global-set-key (kbd "<left-fringe> <mouse-1>") 'bm-toggle-mouse)
(global-set-key (kbd "<right-fringe> <mouse-1>") 'bm-toggle-mouse)
